# role: jomrr.logindefs
# file: molecule/resources/playbooks/verify.yml
# code: language=ansible-jinja

- name: "PLAYBOOK | Verify | logindefs"
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Ensure util-linux is installed"
      ansible.builtin.package:
        name: "util-linux"
        state: "present"

    - name: "Create testuser with useradd"
      ansible.builtin.command:
        cmd: "useradd -m -s /bin/bash testuser"
      register: _useradd
      changed_when: false
      failed_when: _useradd.rc > 0 and not "already exists" in _useradd.stderr

    - name: "Check home directory permissions"
      ansible.builtin.stat:
        path: "/home/testuser"
      register: home_stat

    - name: "Verify home directory permissions"
      ansible.builtin.assert:
        that: home_stat.stat.mode == '0700'
        fail_msg: "Home directory permissions are not 0700"
        success_msg: "Home directory permissions are 0700"

    - name: "Set password for testuser"
      become: true
      become_user: testuser
      ansible.builtin.command:
        cmd: "echo 'testuser:Test123blabla,0815' | chpasswd"
      changed_when: false

    - name: "Check if testuser can login"
      ansible.builtin.command:
        cmd: "su - testuser -c 'whoami'"
      register: _login
      changed_when: false

    - name: "Check if testuser can login"
      ansible.builtin.command:
        cmd: "chage -l testuser"
      register: _chage
      changed_when: false
      failed_when: not '384' in _chage.stdout

    - name: "Clean up test user"
      ansible.builtin.command:
        cmd: "userdel -r testuser"
      changed_when: false
